# Generated by Django 5.0.6 on 2024-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_ost_name_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ost_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='отечество'),
        ),
    ]
