# Generated by Django 4.1.7 on 2026-01-11 09:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
